//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hatate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public byte Similarity {
            get {
                return ((byte)(this["Similarity"]));
            }
            set {
                this["Similarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TagsCount {
            get {
                return ((int)(this["TagsCount"]));
            }
            set {
                this["TagsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Additional")]
        public global::IqdbApi.Enums.MatchType MatchType {
            get {
                return ((global::IqdbApi.Enums.MatchType)(this["MatchType"]));
            }
            set {
                this["MatchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckMatchType {
            get {
                return ((bool)(this["CheckMatchType"]));
            }
            set {
                this["CheckMatchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Delay {
            get {
                return ((int)(this["Delay"]));
            }
            set {
                this["Delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public sbyte Source_Danbooru {
            get {
                return ((sbyte)(this["Source_Danbooru"]));
            }
            set {
                this["Source_Danbooru"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public sbyte Source_Konachan {
            get {
                return ((sbyte)(this["Source_Konachan"]));
            }
            set {
                this["Source_Konachan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public sbyte Source_Yandere {
            get {
                return ((sbyte)(this["Source_Yandere"]));
            }
            set {
                this["Source_Yandere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public sbyte Source_Gelbooru {
            get {
                return ((sbyte)(this["Source_Gelbooru"]));
            }
            set {
                this["Source_Gelbooru"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public sbyte Source_SankakuChannel {
            get {
                return ((sbyte)(this["Source_SankakuChannel"]));
            }
            set {
                this["Source_SankakuChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public sbyte Source_Eshuushuu {
            get {
                return ((sbyte)(this["Source_Eshuushuu"]));
            }
            set {
                this["Source_Eshuushuu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public sbyte Source_TheAnimeGallery {
            get {
                return ((sbyte)(this["Source_TheAnimeGallery"]));
            }
            set {
                this["Source_TheAnimeGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public sbyte Source_Zerochan {
            get {
                return ((sbyte)(this["Source_Zerochan"]));
            }
            set {
                this["Source_Zerochan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public sbyte Source_AnimePictures {
            get {
                return ((sbyte)(this["Source_AnimePictures"]));
            }
            set {
                this["Source_AnimePictures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddRating {
            get {
                return ((bool)(this["AddRating"]));
            }
            set {
                this["AddRating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Randomize {
            get {
                return ((bool)(this["Randomize"]));
            }
            set {
                this["Randomize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSend {
            get {
                return ((bool)(this["AutoSend"]));
            }
            set {
                this["AutoSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AskTags {
            get {
                return ((bool)(this["AskTags"]));
            }
            set {
                this["AskTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HydrusApiPort {
            get {
                return ((string)(this["HydrusApiPort"]));
            }
            set {
                this["HydrusApiPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HydrusApiAccessKey {
            get {
                return ((string)(this["HydrusApiAccessKey"]));
            }
            set {
                this["HydrusApiAccessKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:45869")]
        public string HydrusApiHost {
            get {
                return ((string)(this["HydrusApiHost"]));
            }
            set {
                this["HydrusApiHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HydrusTagService {
            get {
                return ((string)(this["HydrusTagService"]));
            }
            set {
                this["HydrusTagService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddTaggedTag {
            get {
                return ((bool)(this["AddTaggedTag"]));
            }
            set {
                this["AddTaggedTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddNotfoundTag {
            get {
                return ((bool)(this["AddNotfoundTag"]));
            }
            set {
                this["AddNotfoundTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hatate:tagged")]
        public string TaggedTag {
            get {
                return ((string)(this["TaggedTag"]));
            }
            set {
                this["TaggedTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hatate:not found")]
        public string NotfoundTag {
            get {
                return ((string)(this["NotfoundTag"]));
            }
            set {
                this["NotfoundTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddFoundTag {
            get {
                return ((bool)(this["AddFoundTag"]));
            }
            set {
                this["AddFoundTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hatate:found")]
        public string FoundTag {
            get {
                return ((string)(this["FoundTag"]));
            }
            set {
                this["FoundTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteImported {
            get {
                return ((bool)(this["DeleteImported"]));
            }
            set {
                this["DeleteImported"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AssociateUrl {
            get {
                return ((bool)(this["AssociateUrl"]));
            }
            set {
                this["AssociateUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogMatchedUrls {
            get {
                return ((bool)(this["LogMatchedUrls"]));
            }
            set {
                this["LogMatchedUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SendUrlWithTags {
            get {
                return ((bool)(this["SendUrlWithTags"]));
            }
            set {
                this["SendUrlWithTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ParseTags {
            get {
                return ((bool)(this["ParseTags"]));
            }
            set {
                this["ParseTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ResizeImage {
            get {
                return ((bool)(this["ResizeImage"]));
            }
            set {
                this["ResizeImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ThumbWidth {
            get {
                return ((int)(this["ThumbWidth"]));
            }
            set {
                this["ThumbWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte SearchEngine {
            get {
                return ((byte)(this["SearchEngine"]));
            }
            set {
                this["SearchEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoveResultAfter {
            get {
                return ((bool)(this["RemoveResultAfter"]));
            }
            set {
                this["RemoveResultAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public sbyte Source_Pixiv {
            get {
                return ((sbyte)(this["Source_Pixiv"]));
            }
            set {
                this["Source_Pixiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-14")]
        public sbyte Source_Twitter {
            get {
                return ((sbyte)(this["Source_Twitter"]));
            }
            set {
                this["Source_Twitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-17")]
        public sbyte Source_Other {
            get {
                return ((sbyte)(this["Source_Other"]));
            }
            set {
                this["Source_Other"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public sbyte Source_Seiga {
            get {
                return ((sbyte)(this["Source_Seiga"]));
            }
            set {
                this["Source_Seiga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SauceNaoApiKey {
            get {
                return ((string)(this["SauceNaoApiKey"]));
            }
            set {
                this["SauceNaoApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public sbyte Source_DeviantArt {
            get {
                return ((sbyte)(this["Source_DeviantArt"]));
            }
            set {
                this["Source_DeviantArt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public sbyte Source_ArtStation {
            get {
                return ((sbyte)(this["Source_ArtStation"]));
            }
            set {
                this["Source_ArtStation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-13")]
        public sbyte Source_Pawoo {
            get {
                return ((sbyte)(this["Source_Pawoo"]));
            }
            set {
                this["Source_Pawoo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-16")]
        public sbyte Source_MangaDex {
            get {
                return ((sbyte)(this["Source_MangaDex"]));
            }
            set {
                this["Source_MangaDex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartupReleaseCheck {
            get {
                return ((bool)(this["StartupReleaseCheck"]));
            }
            set {
                this["StartupReleaseCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddImagesToHydrusPage {
            get {
                return ((bool)(this["AddImagesToHydrusPage"]));
            }
            set {
                this["AddImagesToHydrusPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files")]
        public string HydrusPageName {
            get {
                return ((string)(this["HydrusPageName"]));
            }
            set {
                this["HydrusPageName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte SearchedParenthesisValue {
            get {
                return ((byte)(this["SearchedParenthesisValue"]));
            }
            set {
                this["SearchedParenthesisValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public byte SimilarityThreshold {
            get {
                return ((byte)(this["SimilarityThreshold"]));
            }
            set {
                this["SimilarityThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte RetryMethod {
            get {
                return ((byte)(this["RetryMethod"]));
            }
            set {
                this["RetryMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sources {
            get {
                return ((string)(this["Sources"]));
            }
            set {
                this["Sources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HydrusTagServiceKey {
            get {
                return ((string)(this["HydrusTagServiceKey"]));
            }
            set {
                this["HydrusTagServiceKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HydrusQuery_InboxOnly {
            get {
                return ((bool)(this["HydrusQuery_InboxOnly"]));
            }
            set {
                this["HydrusQuery_InboxOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HydrusQuery_ArchiveOnly {
            get {
                return ((bool)(this["HydrusQuery_ArchiveOnly"]));
            }
            set {
                this["HydrusQuery_ArchiveOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HydrusQuery_WarnBeforeImport {
            get {
                return ((bool)(this["HydrusQuery_WarnBeforeImport"]));
            }
            set {
                this["HydrusQuery_WarnBeforeImport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint HydrusQuery_Limit {
            get {
                return ((uint)(this["HydrusQuery_Limit"]));
            }
            set {
                this["HydrusQuery_Limit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagSource_User {
            get {
                return ((bool)(this["TagSource_User"]));
            }
            set {
                this["TagSource_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagSource_Booru {
            get {
                return ((bool)(this["TagSource_Booru"]));
            }
            set {
                this["TagSource_Booru"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TagSource_SearchEngine {
            get {
                return ((bool)(this["TagSource_SearchEngine"]));
            }
            set {
                this["TagSource_SearchEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TagSource_Hatate {
            get {
                return ((bool)(this["TagSource_Hatate"]));
            }
            set {
                this["TagSource_Hatate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TagNamespaces {
            get {
                return ((string)(this["TagNamespaces"]));
            }
            set {
                this["TagNamespaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FocusHydrusPage {
            get {
                return ((bool)(this["FocusHydrusPage"]));
            }
            set {
                this["FocusHydrusPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ZerochanTagNamespaces {
            get {
                return ((string)(this["ZerochanTagNamespaces"]));
            }
            set {
                this["ZerochanTagNamespaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte BetterImageRules_PreferedFileFormat {
            get {
                return ((byte)(this["BetterImageRules_PreferedFileFormat"]));
            }
            set {
                this["BetterImageRules_PreferedFileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Hydrus_AutoSendBehaviour {
            get {
                return ((byte)(this["Hydrus_AutoSendBehaviour"]));
            }
            set {
                this["Hydrus_AutoSendBehaviour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte BetterImageRules_WidthComparisonOperator {
            get {
                return ((byte)(this["BetterImageRules_WidthComparisonOperator"]));
            }
            set {
                this["BetterImageRules_WidthComparisonOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte BetterImageRules_HeightComparisonOperator {
            get {
                return ((byte)(this["BetterImageRules_HeightComparisonOperator"]));
            }
            set {
                this["BetterImageRules_HeightComparisonOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte BetterImageRules_SizeComparisonOperator {
            get {
                return ((byte)(this["BetterImageRules_SizeComparisonOperator"]));
            }
            set {
                this["BetterImageRules_SizeComparisonOperator"] = value;
            }
        }
    }
}
